version: '3.7'

services:
  # This runs the database that everything else connects to
  db:
    image: postgres:13
    ports:
      - 9001:5432
    environment:
      POSTGRES_USER: m-nny
      POSTGRES_PASSWORD: 'change-in-production'
      POSTGRES_DB: improved-spoon
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume: